### ISSUE TITLE
Import testing.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/templates-directory#13]
Hey guys! 🕺 
I need some help with testing the importer and see if everything works ok. Here are the steps you need to take in order to set it up and try it out.

1) Create 2 local instances. We'll use one to export the content from it - we'll call it **EXP** from now on. And one for where we're going to import everything - **IMP**.

2) On **EXP** set up a site with **Hestia Pro** and install the demo data export plugin from here - https://github.com/Codeinwp/demo-data-exporter.

3) Set up some content and basic plugins + _Elementor_ and some pages / posts built with Elementor. 

4) Set up the Demo Exporter in the dashboard under **Tools** submenu. It's pretty self-explanatory so shouldn't be a big issue to understand what it does.

5) On **IMP** install Hestia Pro from my fork, the _onboarding_ branch - https://github.com/abaicus/hestia-pro/tree/onboarding

6) Install OrbitFox and run `composer install` inside its' folder.

7) In `wp-content/` create a folder called `mu-plugins` and clone the Template Directory there _sites-lib_ branch - https://github.com/codeinwp/templates-directory/tree/sites-lib.

8) Inside `mu-plugins` create a `must-use.php` file with the following code inside: 
```
<?php 

require_once 'templates-directory/load.php';
```

9) Now _Demo Import_ should be available in the `Appearance > About Hestia Pro` page as a tab. You can access directly: http://import.local/wp-admin/themes.php?page=hestia-pro-welcome#demo-import

10) Another step that you should take in the theme on the **IMP** instance is to add your own instance there. Go inside `wp-content/themes/hestia-pro/inc/core/class-hestia-public.php`and edit the `get_ti_demo_content_support_data` method to add your own local instance in the array.

11) Try importing everything you can. Mostly I'm interested to see how well the builder pages are imported. 

**IMPORTANT:** Please test with dev-tools opened on the network tab and look for any errors that might arise. 
---

If you have any issues doing anything let me know and we'll sort it out. Thanks a bunch! ❤️

**Comment by radu-themeisle** [comment]
I tested @abaicus's latest commit and the importer works properly.

**Comment by stefan-cotitosu** [comment]
@abaicus It is working well on my end.
